version: '{build}'  # This version number is used by AppVeyor to identify the build, NOT the version of the software

environment:
  # This is the version of the software
  VERSION: 1.1.2
  TARGET_CONFIGURATION: Release

image: Visual Studio 2022

platform: Any CPU

branches:
  only:
    - master

only_commits:
  message: /(publish|deploy|build)/

before_build:
- cmd: >-
    dotnet --version

build_script:
- cmd: >-
    dotnet pack .\src\Doulex.DotNetCore -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

artifacts:
  - path: "src/**/*.nupkg"
    name: "NuGet Packages"

deploy:
  - provider: NuGet
    api_key:
      secure: m281r1dMaWVDTd7j0coGCGUQDUBjgBuvmV1d9iD7ueI1AaME/Xx2t7GK3ox/z4UP
    artifact: /.*\.nupkg/
